# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under mlops_demo/resources/*
# and mlops_demo/databricks.yml with staging deployment target configs,
# when PRs are merged into the default branch
name: Bundle Deployment for mlops-demo Staging

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./mlops_demo

env:
  ARM_TENANT_ID: ${{ secrets.STAGING_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.STAGING_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.STAGING_AZURE_SP_CLIENT_SECRET }}
  

jobs:
  staging:
    concurrency: mlops-demo-staging-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Staging
        id: validate
        run: |
          databricks bundle validate -t staging
      - name: Deploy Bundle to Staging
        id: deploy
        run: |
          databricks bundle deploy -t staging
  
  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      # Feature store tests bring up a local Spark session, so Java is required.
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt
            pip install -r ../test-requirements.txt
      - name: Run tests with pytest
        run: |
            pytest

  integration_test:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: 3.8
      - name: Run Feature Engineering Workflow for Test Deployment Target in Staging Workspace
        id: feature_engineering
        run: |
          databricks bundle run write_feature_table_job -t staging
      - name: Run Training Workflow for Test Deployment Target in Staging Workspace
        id: training
        run: |
          databricks bundle run model_training_job -t staging
