# This GitHub workflow deploys Bundle resources (ML resource config and more)
# defined under mlops_demo/resources/*
# and mlops_demo/databricks.yml with prod deployment target configs,
# when PRs are merged into the release branch
name: Bundle Deployment for mlops-demo Prod

on:
  push:
    branches:
      - 'release'
  workflow_dispatch:

defaults:
  run:
    working-directory: ./mlops_demo

env:
  ARM_TENANT_ID: ${{ secrets.PROD_AZURE_SP_TENANT_ID }}
  ARM_CLIENT_ID: ${{ secrets.PROD_AZURE_SP_APPLICATION_ID }}
  ARM_CLIENT_SECRET: ${{ secrets.PROD_AZURE_SP_CLIENT_SECRET }}
  

jobs:
  prod:
    concurrency: mlops-demo-prod-bundle-job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: databricks/setup-cli@v0.221.0
      - name: Validate Bundle For Prod
        id: validate
        run: |
          databricks bundle validate -t prod
      - name: Deploy Bundle to Prod
        id: deploy
        run: |
          databricks bundle deploy -t prod
